//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClient.WCF_PurchaseSystem {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF_PurchaseSystem.IPurchaseSystem")]
    public interface IPurchaseSystem {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseSystem/DoWork", ReplyAction="http://tempuri.org/IPurchaseSystem/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchaseSystem/PO_GetPurchaseOrder", ReplyAction="http://tempuri.org/IPurchaseSystem/PO_GetPurchaseOrderResponse")]
        System.Data.DataSet PO_GetPurchaseOrder(string PONO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPurchaseSystemChannel : WCFClient.WCF_PurchaseSystem.IPurchaseSystem, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PurchaseSystemClient : System.ServiceModel.ClientBase<WCFClient.WCF_PurchaseSystem.IPurchaseSystem>, WCFClient.WCF_PurchaseSystem.IPurchaseSystem {
        
        public PurchaseSystemClient() {
        }
        
        public PurchaseSystemClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PurchaseSystemClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseSystemClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchaseSystemClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Data.DataSet PO_GetPurchaseOrder(string PONO) {
            return base.Channel.PO_GetPurchaseOrder(PONO);
        }
    }
}
